- id: '1664334164626'
  alias: Auto-close Garage at 11 PM
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition:
  - condition: device
    device_id: 4668e12869f12ddbcb9f94a4898cfff9
    domain: cover
    entity_id: cover.garage_door_controller
    type: is_open
  action:
  - device_id: 4668e12869f12ddbcb9f94a4898cfff9
    domain: cover
    entity_id: cover.garage_door_controller
    type: close
  - service: notify.mobile_app_traitorphone
    data:
      message: Auto-closed garage door
  mode: restart
- id: '1668307957780'
  alias: Auto-open when Ben gets home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.ben
    to: home
    for:
      seconds: 15
  - platform: state
    entity_id:
    - person.ben
    to: not_home
  condition:
  - condition: state
    entity_id: device_tracker.tessa_location_tracker
    for:
      minutes: 5
    state:
    - home
    - not_home
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: person.ben
        state: not_home
      sequence:
      - delay:
          minutes: 5
    - conditions:
      - condition: state
        entity_id: person.ben
        state: home
      sequence:
      - device_id: 4668e12869f12ddbcb9f94a4898cfff9
        domain: cover
        entity_id: cover.garage_door_controller
        type: open
      - service: notify.mobile_app_traitorphone
        data:
          title: Auto-Garage Door
          message: You have arrived home and the garage door is opening automatically.
  mode: single
