
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  #base_url: !secret http_base_url
  use_x_forwarded_for: true
  trusted_proxies:
    - '172.20.0.1'
    - '172.20.0.2'
    - '172.20.0.3'
    - '172.20.0.4'
    - '172.20.0.5'
    - '172.20.0.6'
    - '172.20.0.7'
    - '172.20.0.8'
    - '172.20.0.9'
    - '172.20.0.10'
    - '172.20.0.11'
    - '172.20.0.12'
    - '172.20.0.13'
    - '172.20.0.14'
    - '172.20.0.15'
    - '172.20.0.16'

duckdns:
  domain: veleek
  access_token: 4748785b-fed1-4962-8f30-b0398a1055fd

google_domains:
  domain: !secret domain
  username: !secret google_domains_username
  password: !secret google_domains_password
  timeout: 60

google_assistant:
  project_id: !secret ga_project_id
  service_account: !include ga-service-account.json
  api_key: !secret ga_api_key
  secure_devices_pin: !secret ga_secure_devices_pin
  report_state: true
  exposed_domains:
    - switch
    - light
    - cover
    - lock
    - sensor
  entity_config:
    light.bens_light:
      expose: false
    light.katies_light:
      expose: false
    light.baby_light:
      expose: false
    light.reading_light:
      expose: false
    # The kitchen lights are exposed as a light, not as a switch so ignore this.
    switch.kitchen_switch:
      expose: false

light:
  - platform: template
    lights:
      kitchen_light:
        friendly_name: Kitchen Light
        unique_id: kitchen_light_template
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.kitchen_switch
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.kitchen_switch
        level_template: '{% if is_state("switch.kitchen_switch", "on") %}255{%else %}0{%endif%}'
        value_template: '{{ is_state("switch.kitchen_switch", "on") }}'

nest:
  client_secret: !secret nest_client_secret
  client_id: !secret nest_client_id

aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  tfa_source: push
  tfa_type: PUSH
  #tfa_retries: 5
  #tfa_delay: 10

camera:
  - platform: aarlo

binary_sensor:
  - platform: aarlo
    monitored_conditions:
      - motion
      - sound
      - cry
      - connectivity

sensor:
  - platform: aarlo
    monitored_conditions:
      - recent_activity
      - battery_level
      - signal_strength
      - temperature
      - humidity
      - air_quality

# zone:
#   - name: Work
#     latitude: !secret work_latitude
#     longitude: !secret work_longitude
#     radius: 200
#     icon: mdi:laptop-windows

logger:
  default: warn
  logs:
    homeassistant.components.google_domains: debug
    # # Filtering out a bunch of extra noise we don't want
    # homeassistant.setup: warn
    # homeassistant.loader: warn
    # homeassistant.components.http: warn
    # pyhap: warn

    # # We never want debug for this
    # homeassistant.components.websocket_api: info

    # # Some extra info for ZWave stuff
    # homeassistant.components.zwave: info
    # homeassistant.components.zwave.util: info
    # openzwave: warn
    # libopenzwave: warn
    # custom_components.aarlo: debug
    # custom_components.aarlo.alarm_control_panel: debug
    # custom_components.aarlo.binary_sensor: debug
    # custom_components.aarlo.camera: debug
    # custom_components.aarlo.light: debug
    # custom_components.aarlo.media_player: debug
    # custom_components.aarlo.sensor: debug
    # custom_components.aarlo.switch: debug
    # pyaarlo: debug
    # custom_components: debug

prometheus:
  namespace: hass
