homeassistant:
# Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 170
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  server_port: 443
  base_url: !secret http_base_url
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

ios:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

sensor:
  # Weather prediction
  - platform: yr
  # SSL Certificate Monitoring and renewal
  - platform: command_line
    name: SSL cert expiry
    unit_of_measurement: days
    scan_interval: 86400
    command: "ssl-cert-check -b -c /etc/letsencrypt/live/hass.veleek.com/cert.pem | awk '{ print $NF }'"
  
  # Travel times
  #- platform: google_travel_time
  #  name: Ben to Work
  #  api_key: !secret ga_api_key
  #  origin: !secret home_address
  #  destination: !secret work_address

  #- platform: google_travel_time
  #  name: Home to Work
  #  api_key: !secret ga_api_key
  #  origin: zone.home
  #  destination: !secret work_address


shell_command:
  renew_ssl: /usr/bin/certbot renew --quiet --no-self-upgrade --standalone --preferred-challenges http-01

# Text to speech
tts:
  - platform: google

light:
  - platform: hue
    host: 192.168.29.192
  - platform: template
    lights:
      kitchen_light:
        friendly_name: Kitchen Light
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.kitchen_switch
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.kitchen_switch
        level_template: '{% if is_state("switch.kitchen_switch", "on") %}255{%else %}0{%endif%}'
        value_template: '{{ is_state("switch.kitchen_switch", "on") }}'

lock:
  - platform: sesame
    email: !secret email
    password: !secret sesame_password

nest:
  client_secret: !secret nest_client_secret
  client_id: !secret nest_client_id

google_domains:
  domain: !secret domain
  username: !secret google_domains_username
  password: !secret google_domains_password

google_assistant:
  project_id: !secret ga_project_id
  api_key: !secret ga_api_key
  exposed_domains:
    - switch
    - light
    - cover
  entity_config:
    light.bedside_light:
      expose: false
    light.reading_light:
      expose: false
    # The kitchen lights are exposed as a light, not as a switch so ignore this.
    switch.kitchen_switch: 
      expose: false
    light.living_room:
      expose: false
    light.master:
      expose: false

zone:
  - name: Work
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    radius: 200
    icon: mdi:laptop-windows

homekit:
  auto_start: False
  filter:
    include_domains:
      - light

telegram_bot:
  - platform: webhooks
    api_key: !secret telegram_key
    allowed_chat_ids:
      - !secret telegram_ben_id
      - !secret telegram_katie_id
    trusted_networks:
      - 149.154.167.197/32
      - 149.154.167.198/31
      - 149.154.167.200/29
      - 149.154.167.208/28
      - 149.154.167.224/29
      - 149.154.167.232/31
      - 192.168.29.0/24

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zwave: !include zwave.yaml

cover: 
  - platform: zwave
    device_class: garage

lovelace:
  mode: yaml

notify:
#  - name: gmail
#    platform: smtp
#    server: smtp.gmail.com
#    port: 587
#    timeout: 15
#    sender: !secret email
#    encryption: starttls
#    username: !secret email
#    password: !secret password
#    recipient:
#      - !secret email
#    sender_name: My Home Assistant
  - name: telegram_ben
    platform: telegram
    chat_id: !secret telegram_ben_id

logger:
  default: info  
  logs:
    # Filtering out a bunch of extra noise we don't want
    homeassistant.setup: warn
    homeassistant.loader: warn
    homeassistant.components.http: warn

    # We never want debug for this
    homeassistant.components.websocket_api: info

    # Some extra info for ZWave stuff
    homeassistant.components.zwave: debug
    homeassistant.components.zwave.util: info
    openzwave: warn
    libopenzwave: warn
