#!/bin/bash

if [ "$(id -u)" != "0" ]; then
echo "This script must be run with sudo. Use \"sudo ${0} ${*}\"" 1>&2
exit 1
fi

#echo "Changing to user homeassistant"
#sudo -H -u homeassistant /bin/bash <<EOF
#echo "Activating virtual environment"
#source /srv/homeassistant/homeassistant_venv/bin/activate
cd /home/pi/homeassistant
. ./bin/activate

# install cython if not already installed
pip3 install --upgrade cython==0.24.1

# remove previously install python_openzwave
pip3 uninstall -y python_openzwave

# install regular flavor of python_openzwave
pip3 install --no-cache-dir 'python_openzwave==0.4.18'

exit 0
