title: Bear Creek

resources: 
  - url: /local/mini-media-player-bundle.js?v=0.9.8
    type: module
  - url: /local/monster-card.js?v=1
    type: module

views:
  - title: New
    icon: mdi:test-tube
    cards:
      - type: thermostat
        title: Climate
        entity: climate.dining_room_nest
      - type: history-graph
        title: Temperature History
        hours_to_show: 12
        entities:
          - sensor.dining_room_thermostat_temperature
          - sensor.entrysensor_temperature
          - sensor.aeotec_zw100_multisensor_6_temperature
          - sensor.dining_room_thermostat_target
         # - climate.dining_room_nest.target_temp_high
         # - climate.dining_room_nest.target_temp_low
      - type: entities
        title: Security
        show_header_toggle: false
        entities:
          - lock.home
          - cover.garage_door_barrier_state
      - type: entities
        title: Lights
        entities:
          - light.bedside_light
          - light.dining_level
          - light.entry_level
          - light.kitchen_light
          - light.living_level
          - light.office_level
          - light.reading_light
      - type: vertical-stack
        cards:
          - type: custom:mini-media-player
            entity: media_player.den
          - type: custom:mini-media-player
            entity: media_player.bedroom_speaker
          - type: custom:mini-media-player
            entity: media_player.kitchen_display
          - type: custom:mini-media-player
            entity: media_player.home
      - type: picture-entity
        title: Cameras
        entity: camera.entryway
  - title: Details
    path: details
    cards: 
      - type: custom:monster-card
        card:
          title: Automations
          type: entities
        filter:
          include:
            - domain: automation
      - type: custom:monster-card
        card:
          title: Sensors
          type: entities
          show_header_toggle: false;
        filter:
          include:
            - domain: binary_sensor
            - domain: sensor
      - type: custom:monster-card
        card:
          title: ZWave Nodes
          type: entities
          show_header_toggle: false;
        filter:
          include:
            - domain: zwave

      - type: custom:monster-card
        card:
          title: Switches
          type: entities
          show_header_toggle: false;
        filter:
          include:
            - domain: light
            - domain: switch
